### PR TITLE
Hotfix/validators.with param async

### LINKED ISSUE #31: validators.withParam does not work with async validators
Currently validators.withParam only accepts sync validators. I'd like to use it with async validators too.

### PR DESCRIPTION
**Pull request by maschino**
### Summary
Makes `validators.withParam` generic. Fixes #31 

### Checklist
Please ensure that you've fulfilled the following tasks:
* [x] My code follows the style guides of this project and `yarn lint` does not throw errors
* [x] My code is well tested and did not decrease the test coverage
* [x] All new and existing tests have passed
* [ ] My submission passes the build
* [x] I've added changes to [CHANGELOG.MD](./CHANGELOG.MD)
* [ ] I've updated the project documentation

### CODE REVIEW

File: src/validators/validators.ts [hunk 1]
```diff
@@ -7,16 +7,16 @@
...
 /**
  * Wrapper function to call validators with parameters
  * @param validator function to call
  * @param context form context
  * @param args parameters for the validator
  */
-const withParam = (validator: TValidator, ...args: unknown[]): TValidator => {
-  return (value: TBasicFieldValue, context: IFormContext): TFieldError => validator(value, context, args);
+const withParam = <TCallback extends TValidator | TAsyncValidator>(validator: TCallback, ...args: unknown[]): TCallback => {
+  return (value: TBasicFieldValue, context: IFormContext): ReturnType<TCallback> => validator(value, context, args);
```
Comment (maschino) [inline src/validators/validators.ts]: @christophka In raw javascript the withParam method can already deal with asyncValidators. It's only the type checking that makes issues. I've tried to make withParam generic, but typescript complains about my return type. Can you take a look at that?

**Comment by christophka** [comment]
I will try to look at it today

File: src/validators/validators.ts (hunk 1 above)
Comment (christophka) [reply src/validators/validators.ts]: So the problem seems to be the union type for TCallback regarding the sync / async. Also the build-in type `ReturnType` also seems to fail with this kind of setup.

So i changed it, so that we have the union type only for the return value for the validator. so instead of `<TCallback extends TValidator | TAsyncValidator>` I introduced a new type that returns a promise or not. that seems to fix the problem. Also the return type then can be infered correctly

File: src/validators/validators.types.ts [hunk 2]
```diff
@@ -62,6 +62,12 @@ export type TValidator = ((value: TBasicFieldValue | undefined, context: IFormCo
  * Async validator method type
  */
 export type TAsyncValidator = ((value: TBasicFieldValue | undefined, context: IFormContext, ...args: unknown[]) => Promise<TFieldError>);
+/**
+ * A validator that may be async or not
+ */
+export type TAnyValidator = (
+  (value: TBasicFieldValue | undefined, context: IFormContext, ...args: unknown[]) => TFieldError | Promise<TFieldError>
```
Comment (christophka) [inline src/validators/validators.types.ts]: @maschino thats the new validator type definitino

File: src/validators/validators.ts [hunk 3]
```diff
@@ -7,16 +7,16 @@
...
-import { FieldErrorMessageId, TAsyncValidator, TFieldError, TValidator } from './validators.types';
+import { FieldErrorMessageId, TAnyValidator, TFieldError } from './validators.types';
 
 /**
  * Wrapper function to call validators with parameters
  * @param validator function to call
  * @param context form context
  * @param args parameters for the validator
  */
-const withParam = <TCallback extends TValidator | TAsyncValidator>(validator: TCallback, ...args: unknown[]): TCallback => {
```
Comment (christophka) [inline src/validators/validators.ts]: @maschino 
I also had to change the return type here to `TAnyValidator`. I am not sure how the union type return values work in combination with extends.
It's not the best solution but it works for now

**Comment by christophka** [comment]
@maschino have a look at my changes. maybe we can still improve the solution and this will put us in the right direction

**Comment by maschino** [comment]
Just tried it with the typescript 3.3 RC version - it throws the same error on my simple test. Maybe we should keep it simple and just provide a `validators.withParamAsync` helper method. What do you think @christophka?
